version: '3'

services:
  jira:
    build: .
    container_name: jira
    ports:
      - "8080:8080"
    environment:
      ATL_JDBC_URL: jdbc:postgresql://192.168.2.110:5432/jiradb
      ATL_JDBC_USER: jirauser
      ATL_JDBC_PASSWORD: Tlm@101195
    depends_on:
      - db
    volumes:
      - jira_data:/var/atlassian/application-data/jira

  db:
    image: postgres:12.20-alpine
    container_name: jira_db
    environment:
      POSTGRES_DB: jiradb
      POSTGRES_USER: jirauser
      POSTGRES_PASSWORD: Tlm@101195
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: jira_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - jira

volumes:
  jira_data:
  db_data:

